server:
  port: 9002


spring:
  application:
    name: betazone-hello-remotename
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      zone: beta

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: beta #服务区域
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/


logging:
  level:
    org.springframework.cloud: debug
