server:
  port: 8103

spring:
  application:
    name: betazone-hello-nameservice
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: beta # zone服务区域 beta
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/


logging:
  level:
    org.springframework.cloud: debug
