server:
  port: 8801

spring:
  application:
    name: betazone-hello-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: default
          uri: lb://betazone-hello-nameserviceSwaggerResourcesProvider
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: remotename
          uri: lb://betazone-hello-remotename
          predicates:
            - Path=/remoteapi/**
          filters:
            - StripPrefix=1
    loadbalancer:
      ribbon:
        enabled: false
      zone: main
      #configurations: zone-preference

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: main
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka/


logging:
  level:
    org.springframework.cloud: debug
